### ISSUE TITLE
How to pass flags to a formatter

### ISSUE THREAD

**Issue by mohitsakhuja** [google/vim-codefmt#105]
I would just like to know how to pass flags to a formatter, particularly I'm asking for Autopep8. I usually format the code with `--aggressive` option but I can't seem to be able to do that using this. I read the documentation in the `vroom/` and `doc/` directories but I couldn't find a way on how to do this. I understand if this is a noobie question - which it is, since I am new to Vim and Vimscript. So any help would be appreciated.

**Comment by dbarnett** [comment]
Can that option be enabled in autopep8's .pycodestyle file?
https://github.com/hhatto/autopep8/blob/master/README.rst#configuration

**Comment by nfischer** [comment]
Just hit this as well. I'd like to use `js-beautify -s 2` (2-space indent instead of 4). I wound up using a similar workaround with `.jsbeautifyrc`.

I agree in principle this is better configured per-project in a config file, although my specific case is to send a one-off fix (I'm not committing the config file since my team doesn't regularly use this tool). Perhaps we could put a warning in the README, explaining multi-arg commands (including CLI switches) aren't supported, and users should consider config files for their formatters?

**Comment by dbarnett** [comment]
I think #66 covers this and we can mark this one a dupe.

We have some more discussion on it there. Local config files are definitely a better option where available.
