### ISSUE TITLE
Error formatting file: ERROR(NotFound): Python module maktaba

### ISSUE THREAD

**Issue by rickrickrickyyy** [google/vim-codefmt#122]
Error formatting file: ERROR(NotFound): Python module maktaba

how to install it?

**Comment by dbarnett** [comment]
It sounds like maybe you have parts of maktaba installed but they can't find their python files? There's not a maktaba module to install, but the [maktaba vim plugin](https://github.com/google/vim-maktaba) that codefmt uses has some python files it loads from its own directories: https://github.com/google/vim-maktaba/blob/master/python/maktaba.py.

**Comment by rickrickrickyyy** [comment]
I have just checked my vim plugins , it has maktaba vim plugin installed, but it looks like the python file is not loaded automatically.

```

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim_runtime/my_plugins/Vundle.vim
call vundle#begin('~/.vim_runtime/my_plugins')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'google/vim-maktaba'
Plugin 'google/vim-codefmt'
Plugin 'google/vim-glaive'

call vundle#end()            " required
call maktaba#plugin#Detect()
call glaive#Install()
Glaive codefmt plugin[mappings]
filetype plugin indent on    " required
```

**Comment by dbarnett** [comment]
Can you clarify "looks like the python file is not loaded automatically"?

The loading isn't supposed to be automatic. It gets loaded from explicit path path in the vim plugins, like at https://github.com/google/vim-maktaba/blob/ec7a094e602babc2e0d43dc5fa5411e46e3bd70c/autoload/maktaba/buffer.vim#L88. It sounds like something's going wrong with finding and loading the maktaba.py file, but the error you posted doesn't give any information about what. If there were any other relevant lines of error output in `:messages` or sent to the terminal stderr stream after you closed vim, please post those. Otherwise, maybe you need to do something like `vim -V9 vim.log` (see details in http://inlehmansterms.net/2014/10/31/debugging-vim/#general-debugging-with-verbose) to get verbose details.

But at any rate, it's not some missing install step, it's something that normally works and on your system for some reason isn't working.

**Comment by rickrickrickyyy** [comment]
Problem solved after installing [macvim](https://github.com/macvim-dev/macvim). My original vim was the default vim for mac os.

Thank you for taking time out to answer my question

**Comment by dbarnett** [comment]
See google/vim-maktaba#231. I found and fixed some corner cases in `maktaba#python#ImportModule` that should get you clearer error messages for import problems in general and might have fixed the particular failure that blew up here.

**Comment by TamaMcGlinn** [comment]
I'm getting this error now even with a minimal vimrc:

```
" Required:
set runtimepath+=~/minimal_vimscripts/dein/repos/github.com/Shougo/dein.vim
call dein#begin('~/minimal_vimscripts/dein', ['~/minimal.vimrc'])

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')
call dein#add('google/vim-codefmt')
call dein#add('google/vim-maktaba')
" Required:
call dein#end()

let dein#enable_notification = 1

" Required:
filetype plugin indent on

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```
