### ISSUE TITLE
Allow loading formatters from other vim plugins

### ISSUE THREAD

**Issue by yegle** [google/vim-codefmt#157]
**Is your feature request related to a problem? Please describe.**
I might have missed it from the doc, but it seems like the only way to add a new formatter used by codefmt is to send a PR.

The [ale linter](https://github.com/dense-analysis/ale) supports automatically loading a new linter from other vim plugins as long as the file is placed in a particular location. Doc to this feature: https://github.com/dense-analysis/ale/blob/f4668c751fba1af496d933af9fdcf1cf162a26f4/doc/ale.txt#L3530-L3557

This is how a linter for beancount (a very niche tool) can be added to ale and can be maintained outside of ale's repo: https://github.com/nathangrigg/vim-beancount/tree/master/ale_linters/beancount

**Describe the solution you'd like**
Do something like https://github.com/dense-analysis/ale/blob/f4668c751fba1af496d933af9fdcf1cf162a26f4/doc/ale.txt#L3530-L3557

**Describe alternatives you've considered**
Send a PR to implement the new formatter in codefmt.

**Additional context**

**Comment by dbarnett** [comment]
Yes, it's totally possible following the same basic instructions as in https://github.com/google/vim-codefmt#creating-a-new-formatter and this example: https://github.com/google/vim-codefmt/blob/90335990808167d910671a625f3ee9de9aac1058/doc/codefmt.txt#L176-L182

The file locations in those examples are all just suggestions. You just need the maktaba plugin installed for that call to work since that's the vehicle for passing config between plugins. And then since you seem to be bundling that into a separate plugin, you might still consider updating codefmt's generated docs to list it as an available integration, starting a list of not-built-in formatters parallel to the one here: https://github.com/google/vim-codefmt/blob/90335990808167d910671a625f3ee9de9aac1058/autoload/codefmt.vim#L28.

**Comment by yegle** [comment]
Ah I see, guess I should read the doc more carefully. Thank you for the hint!

**Comment by dbarnett** [comment]
You bet! The existing docs were a little confusing for that case and instead emphasized reaching out to us to discuss integrations (so "working as intended" here, I guess!). Happy to help if anything else isn't working as expected.

**Comment by agriffis** [comment]
@yegle I just started fiddling with an out-of-tree formatter too. Looking forward to seeing yours.
