### ISSUE TITLE
Format width

### ISSUE THREAD

**Issue by Ahanaf-Ether** [google/vim-codefmt#184]
Addtional option to add text max width, in prettier there is an option to set max print width, So if i set for ex:
let g:vim_codfmt_print_width = 80
And therfore it will respect the line length under 80 chars per line. Thank you!

**Comment by dbarnett** [comment]
I think many of the formatters do have their own config settings for text width. Is there one you're asking about in particular?

**Comment by Ahanaf-Ether** [comment]
sure width=80

**Comment by Ahanaf-Ether** [comment]
since 80 is a sane choice and mostly consider standard there should be an option to do so, Thank a lot.

**Comment by dbarnett** [comment]
I mean is it a particular language you're wanting to format? Codefmt is just a frontend for invoking different formatter tools for different languages.

**Comment by zhuxiaoxuhit** [comment]
How to set the max length for python？

**Comment by Ahanaf-Ether** [comment]
I figured the easiest way would be to just use a python formatter like
"black"

**Comment by dbarnett** [comment]
So then you're in python and were wanting autopep8 or yapf to accept a line length before? autopep8 does accept a `max_line_length` option and yapf calls it `column_limit`.

We recommend configuring those via the formatter's config files in your project instead of wiring up custom command-line args via vim, so that you get the same results when you trigger the formatter inside and outside of vim.

**Comment by Ahanaf-Ether** [comment]
Yes, exactly.
