### ISSUE TITLE
 vim-codefmt google-java-format 4 spaces instead of 2

### ISSUE THREAD

**Issue by ssh352** [google/vim-codefmt#196]
I've already used Neovim vim-codefmt and google-java-format to format java code . It is a nice plugin but I'd like to customize google-java-format to use 4 spaces instead of 2 for indents.

Is it possible to have google-java-format to read intellij-java-google-style.xml and respect settings in the xml configuration file?

**Comment by malcolmr** [comment]
This is more a question for google-java-format, not vim-codefmt.

If you actually want Android's [AOSP style](https://source.android.com/setup/contribute/code-style), which does use 4-space indents, then you could try using google-java-format's `--aosp` flag with e.g.

```viml
Glaive codefmt google_java_executable='google-java-format --aosp'
```

Otherwise, no, I don't think you can configure that formatter for a different indent; see https://github.com/google/google-java-format/wiki/FAQ#i-just-need-to-configure-it-a-bit-differently-how
