### ISSUE TITLE
yapf code formatting deletes file if it does not parse

### ISSUE THREAD

**Issue by achalddave** [google/vim-codefmt#61]
If you have a file that does not parse correctly by Python, yapf returns an error, and does not print anything to stdout. codefmt reads the stdout from yapf, and replaces the vim buffer with it, which means that a file with the below contents (note the missing end quote)

```
print 'hello
```

will be emptied when codefmt is run.

**Comment by dbarnett** [comment]
Eesh, sounds like it's not checking exit code. Should be an easy fix.

**Comment by scottstanie** [comment]
This is still happening to me, but as a result of a strange corner case.

I installed `yapf` using `conda`, originally with Python 3.6. I switch the python version to 3.8, which I thought was supposed to reinstall all packages. However, when I run `yapf` from the command line, I get this error:

```bash
$ ~/miniconda3/envs/mapping/bin/yapf
-bash: /home/scott/miniconda3/envs/mapping/bin/yapf: /home/scott/miniconda3/envs/mapping/bin/python3.6: bad interpreter: No such file or directory
```

It's definitely this same issue, as when I change the line `autocmd FileType python AutoFormatBuffer yapf` in my .vimrc to `autocmd FileType python AutoFormatBuffer autopep8`, the deleting bug goes away.

Also, I was able to solve this by uninstalling yapf and reinstalling, so that the bad interpreter error went away, but it seemed worth noting here.

**Comment by dbarnett** [comment]
I suspect the remaining issue is that it's returning a non-zero exit code besides `1`. The fix only checked if the exit code was 1 (`v:shell_error == 1`), but any non-zero exit code indicates the command failed.

**Comment by agriffis** [comment]
Bad interpreter is exit code 126

**Comment by dbarnett** [comment]
Yup, that's what I was seeing. I'm going to go ahead and loosen that `v:shell_error == 1` to any non-zero exit code and mark this fixed again. Then I can check if that gives us any interesting new results for #164.
