### ISSUE TITLE
FormatCode with clang-format removes the newline at end of the file

### ISSUE THREAD

**Issue by zbowling** [google/vim-codefmt#83]
Newline at the end of the file required at my company. Please preserve.

**Comment by malcolmr** [comment]
The newline at the end of the file is controlled by Vim's `&endofline` option. `:FormatCode` can't affect that, since it just edits Vim's buffer, which is just a list of lines (and so by default Vim will always write out a newline right at the end of a file).

However, it is true that clang-format appears to strip _extra_ blank lines from the end of a file, leaving just a single newline at the end of a file. I assume that's what you're referring to?

```
$ cat /tmp/foo.cc
#include <vector>

void foo() {
  std::vector v;
}


$ clang-format /tmp/foo.cc 
#include <vector>

void foo() { std::vector v; }
$
```

If this is a problem for you (i.e. if your company mandates files end with `\n\n` for some reason), it's seems like it would affect using `clang-format` outside of Vim? If so, probably best to take it up with the clang-format folks, since codefmt just shells out to clang-format itself for formatting.

(I don't see any of the existing clang-format style options that would help, unfortunately, or you could just create a `.clang-format` file or similar. There is https://bugs.llvm.org//show_bug.cgi?id=21699, requesting empty lines be retained within the end of blocks, but it sounds like maybe you want them retained after the block instead.)

**Comment by ericcurtin** [comment]
Just to solve curiosity on why some companies mandate a new line at the end of file, it's because some compilers don't add a new line when the #include. This can lead to issues, as two lines can get mashed together which weren't intended to be.

So most likely this project is supporting one of those compilers. Or this thing is hanging around from a time when one of those compilers was supported. Or maybe this project intends on supporting one of these in the future!

Modern compilers like gcc, clang and visual studio add a new line on every include, so it's not really an issue with those ones.
